const ERR_PREFIX_SYSTEM = 0x00
const ERR_PREFIX_USER = 0x01000000
const ERR_PREFIX_DATA = 0x02000000
const ERR_PREFIX_ACCESS = 0x03000000

/* ACCESS ERRORS */
export const ErrorCodes = {

    // AxiosError
    ERR_AXIOS_FAILED: -1,


    // System error
    ERR_SYSTEM_ABNORMAL_ACCESS_ERR: ERR_PREFIX_SYSTEM | 0x03,

    // User Error
    ERR_LOGIN_FAILED: ERR_PREFIX_USER | 0x4,

    // Access Error
    ERR_AUTH_ACCESS_ERR: ERR_PREFIX_ACCESS | 0x1,
    ERR_SESSION_EXPIRATION_ERR: ERR_PREFIX_ACCESS | 0x2,

    // Data Error
    ERR_DIR_ALEADY_EXISTS_ERR: ERR_PREFIX_DATA | 0x4,
    ERR_FILE_ALEADY_EXISTS_ERR: ERR_PREFIX_DATA | 0x05,
    ERR_STORAGE_OVER_CAPACITY_ERR: ERR_PREFIX_DATA | 0x6,


};