# Generated by Django 3.2.5 on 2021-08-08 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('static_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16)),
                ('pswd', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=256)),
                ('volume_type', models.CharField(max_length=32)),
                ('is_admin', models.BooleanField()),
            ],
        ),
    ]
