# Generated by Django 3.2.5 on 2021-08-22 04:18

from django.db import migrations, models
import module.validator.user_validator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('static_id', models.CharField(max_length=40, primary_key=True, serialize=False, validators=[module.validator.user_validator.UserValidator.validate_static_id])),
                ('name', models.CharField(max_length=16, validators=[module.validator.user_validator.UserValidator.validate_name])),
                ('pswd', models.CharField(max_length=128, validators=[module.validator.user_validator.UserValidator.validate_password])),
                ('email', models.EmailField(max_length=256, validators=[module.validator.user_validator.UserValidator.validate_email])),
                ('volume_type', models.CharField(max_length=32)),
                ('is_admin', models.BooleanField(validators=[module.validator.user_validator.UserValidator.validate_is_admin])),
            ],
        ),
    ]
