# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  python: circleci/python@1.2

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  test-for-coverage:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: make venv
          command: |
            cd app/server
            python -m venv venv venv
            source venv/bin/activate
            pip install --upgrade pip

      - run:
          name: install python packages
          comnand: |
            cd ..
            pip install -r requirements.txt
            



# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - test-for-coverage
